Repository airlift/airbase, pull requests merged in 2024-08, with the labels that each got.

#423 Add dependabot configuration
  .github/dependabot.yml
Labels: improvement

#417 Remove `InterfaceIsType` checkstyle module
  airbase-policy/src/main/resources/checkstyle/airbase-checks.xml
Labels: improvement

#422 Remove eclipse compiler profile
  airbase/pom.xml
Labels: breaking, cleanup

#453 Use separate property for alpha OpenTelemetry packages version
  airbase/pom.xml
Labels: improvement

#474 Add opentelemetry-semconv to managed dependencies
  airbase/pom.xml
Labels: dependency
