Repository airlift/airbase, pull requests merged in 2024-10, with the labels that each got.

#539 Move checkstyle configuration from execution to plugin
  airbase/pom.xml
Labels: improvement

#546 Upgrade ASM in maven-compiler-plugin
  airbase/pom.xml
Labels: bug, dependency, improvement

#553 Test out early access JReleaser github action
  .github/workflows/release.yml
Labels: bug

#555 Fix master branch
  airbase-policy/pom.xml
  airbase/pom.xml
  pom.xml
Labels: ignore-for-release
